Ledger/Models/Filters.cs
using Common.Core;
using System.Collections.Generic;

namespace Ledger.Models
{
    public class Filters
    {
        public int StateId { get; set; }

        public List<State> States { get; set; }
    }
}

Ledger/Controllers/AdvertisingController.cs
using Ledger.Models;
using Ledger.SpamServices;
using System.Web.Mvc;

namespace Ledger.Controllers
{
    public class AdvertisingController : Controller
    {
        public ActionResult Index()
        {
            return PartialView();
        }

        public ActionResult GetSpam()
        {
            SpamServiceClient spam = new SpamServiceClient();

            var image = spam.GetSpam();

            return File(image.Image, image.Type);
        }
    }
}

Ledger/Controllers/FiltersController.cs
using BusinessLogicLayer.Interfaces;
using Common.Core;
using Common.Models;
using Ledger.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ledger.Controllers
{
    public class FiltersController : Controller
    {
        IBusinessLogic db;

        public FiltersController(IBusinessLogic db)
        {
            this.db = db;
        }

        public ActionResult Index()
        {
            Filters filter = new Filters();
            filter.States = db.Subjects.GetAllStates();
            filter.States.Add(new State { Id = 0, Name = "Нет" });
            return PartialView(filter);
        }

        public ActionResult GetSubjects(int id)
        {
            if(id != 0)
            {
                IEnumerable<Subject> subjects = db.Subjects.GetSubjects().Where(s => s.StateId == id);
                if(subjects.Count() == 0)
                {
                    return PartialView(db.Subjects.GetSubjects());
                }
                return PartialView(subjects);
            }

            return PartialView(db.Subjects.GetSubjects());
        }
    }
}

Ledger/Views/Filters/GetSubjects.cshtml
@model IEnumerable<Common.Core.Subject>

<table class="table table-bordered table-striped" id="mytable">
    <thead>
        <tr role="row">
            <th>Имя</th>
            <th>Номер</th>
            <th>Описание</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var v in Model)
        {
            <tr>
                <td><a href="/Subject/Details/@v.Id" class="compItem" data-toggle="modal">@v.Name</a></td>
                <td>@v.InventoryNumber</td>
                <td>@v.Description</td>
            </tr>
        }
    </tbody>
</table>

Ledger/Views/Filters/Index.cshtml
@model Ledger.Models.Filters

<div class="col-md-2">
    <h4>Фильтры</h4>
    <hr />
    <div class="border">
        <p>По состоянию</p>
        <div class="col-10">
            @Html.DropDownListFor(model => model.StateId, new SelectList(Model.States, "Id", "Name", Model.StateId), new { id = "filerStates" })
            <input id="filterButton" type="button" value="Выбрать" class="btn btn-outline-success my-2 my-sm-0" />
        </div>
    </div>
    <hr />
    <div>
        @Html.Action("Index", "Advertising")
    </div>
</div>