Ledger/Controllers/FiltersController.cs
using BusinessLogicLayer.Interfaces;
using Common.Core;
using Common.Models;
using Ledger.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ledger.Controllers
{
    public class FiltersController : Controller
    {
        IBusinessLogic db;

        public FiltersController(IBusinessLogic db)
        {
            this.db = db;
        }

        public ActionResult Index()
        {
            Filters filter = new Filters();
            filter.States = db.Subjects.GetAllStates();
            filter.States.Add(new State { Id = 0, Name = "Нет" });
            return PartialView(filter);
        }

        public ActionResult GetSubjects(int id)
        {
            if(id != 0)
            {
                IEnumerable<Subject> subjects = db.Subjects.GetSubjects().Where(s => s.StateId == id);
                if(subjects.Count() == 0)
                {
                    return PartialView(db.Subjects.GetSubjects());
                }
                return PartialView(subjects);
            }

            return PartialView(db.Subjects.GetSubjects());
        }
    }
}

Ledger/Controllers/LocationController.cs
using BusinessLogicLayer.Interfaces;
using System.Web.Mvc;

namespace Ledger.Controllers
{
    public class LocationController : Controller
    {
        IBusinessLogic _db;

        public LocationController(IBusinessLogic db)
        {
            _db = db;
        }

        public ActionResult Location()
        {
            SelectList buildings = new SelectList(_db.Locations.GetBuildings(), "Id", "Name");
            SelectList floots = new SelectList(_db.Locations.GetFloots(1), "Id", "Name", "BuildingId");
            SelectList rooms = new SelectList(_db.Locations.GetRooms(1), "Id", "Name", "FlootId");

            ViewBag.Buildings = buildings;
            ViewBag.Floots = floots;
            ViewBag.Rooms = rooms;

            return PartialView();
        }

        public ActionResult Floots(int id)
        {
            return PartialView(_db.Locations.GetFloots(id));
        }

        public ActionResult Rooms(int id)
        {
            return PartialView(_db.Locations.GetRooms(id));
        }
    }
}

Ledger/Views/Shared/NavBarLogin.cshtml
<div class="collapse navbar-collapse">
    @if (Request.IsAuthenticated)
    {
        <form action="Account/Login">

            @Html.AntiForgeryToken()

            <ul navbar-nav mr-auto>
                <li class="nav-item active">
                    <a href="/Account/LogOff" class="btn btn-outline-success my-2 my-sm-0">Выйти</a>
                </li>
            </ul>

        </form>
    }
    else
    {
        <ul>
            <li class="nav-item active">
                <a href="/Account/Login" class="btn btn-outline-success my-2 my-sm-0">Войти</a>
            </li>
        </ul>
    }
</div>

Ledger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
</head>
<body>
    <div id="modDialog" class="modal fade">
        <div id="dialogContent" class="modal-dialog"></div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">

        <a class="navbar-brand" href="/Home">Главная</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/Home/About">О программе <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>

        @Html.Partial("NavBarLogin")

    </nav>
    <div>
        <hr />
    </div>
    <div class="container body-content col-md-10">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – учебный проект Курпаченко Романа</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)

    <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".compItem").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>

    <script type="text/javascript">
         $(function ()
         {
             $('#buildings').change(function ()
             {
                // получаем выбранный id
                var id = $(this).val();
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Floots", "Location")/' + id,
                    success: function (data)
                    {
                        $('#floots').replaceWith(data);
                        $(function ()
                        {
                            $('#floots').click(function ()
                            {
                                // получаем выбранный id
                                var id = $(this).val();
                                $.ajax({
                                    type: 'GET',
                                    url: '@Url.Action("Rooms", "Location")/' + id,
                                    success: function (data)
                                    {
                                        $('#rooms').replaceWith(data);
                                    }
                                });
                            });
                        })
                    }
                });
             });
        })
    </script>
    <script type="text/javascript">
        $(function ()
         {
             $('#floots').click(function ()
             {
                // получаем выбранный id
                var id = $(this).val();
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("Rooms", "Location")/' + id,
                    success: function (data)
                    {
                        $('#rooms').replaceWith(data);
                    }
                });
             });
         })
    </script>

    <script>
        $(document).ready(function () {
            $("#search").keyup(function () {
                _this = this;

                $.each($("#mytable tbody tr"), function () {
                    if ($(this).text().toLowerCase().indexOf($(_this).val().toLowerCase()) === -1) {
                        $(this).hide();
                    } else {
                        $(this).show();
                    }
                });
            });
        });
    </script>

    <script type="text/javascript">
        $(function ()
        {
            $('#filterButton').click(function ()
            {
                var id = $('#filerStates').val();
                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetSubjects", "Filters")/' + id,
                    success: function (data)
                    {
                        $('#mytable').replaceWith(data);
                    }
                });
             });
         })
    </script>
</body>
</html>